new function has been made
shreybatra/Twitter-Stream-API-Dataset pull request #15
Opened 2018-10-01 13:34 UTC by ayushi02

function to remove redundancy in streamtest.py

2018-10-01 15:48 UTC, shreybatra requested changes

2018-10-01 15:48 UTC, shreybatra commented on streamtest.py
> +def func():
Rename ```func()``` to ```get_tweets_from_db()```

2018-10-01 17:55 UTC, ayushi02 commented on streamtest.py
> +def func():
done

2018-10-02 06:02 UTC, shreybatra commented
fix #6

2018-10-02 06:02 UTC, shreybatra approved these changes

2018-10-02 06:02 UTC, merged